### ISSUE TITLE
Cutup Front End Templates

### ISSUE THREAD

**Issue by jeffAwesome** [jeffAwesome/LR#2]
You will need to cutup the following templates into html first. 

Some Notes Please keep HTML Clean and same with CSS. We are going to use Bootstrap Primarily... and only use ids for things we can hook onto later. 

Please try to use semantic code so it will be easier to integrate into rails when it comes time.
- [x] login
- [x] mycontent
- [x] mycontent_drafts
- [x] mycontent_public
- [x] publish_hashtag
- [x] report user
- [x] search
- [x] search no results
- [x] serchresults
- [x] searchresults_people

**Comment by vdumitraskovic** [comment]
Hi. I got some work done. I'm not sure where to put it, so I just temporarily uploaded it to my website. Check http://vdumitraskovic.com/LR/ and look if everything is OK.

**Comment by jeffAwesome** [comment]
Most of these look pretty good. Can you double check and make sure they are as close to the design as possible? And then possibly work on making them semi responsive. We are in the progress of getting the backend stuff ready so you guys can integrate.

**Comment by vdumitraskovic** [comment]
They are very close to the design and responsive. I would need id's and possibly some patterns to clean CSS (sass actually) even more.

**Comment by vdumitraskovic** [comment]
Images are missing on server. Will fix that. Can I help integrating views?
