### ISSUE TITLE
Remainder Desktop Views

### ISSUE THREAD

**Issue by jeffAwesome** [jeffAwesome/LR#3]
These are the last few views before we start integrating.
- [ ] StoryPage
- [ ] StoryPage_AlterCall
- [ ] StoryPage_comment
- [ ] SoryPage_share
- [ ] User_Profile

**Comment by vishalchinchane** [comment]
Hello Jeff,

I have done following view in html. Please check and let me know your comments.

The responsive part is also done(but need some smaller changes)

http://121.243.211.187/vishal/html/loverealm/user_profile.html
http://121.243.211.187/vishal/html/loverealm/storypage.html
http://121.243.211.187/vishal/html/loverealm/storypage_aftercall.html
http://121.243.211.187/vishal/html/loverealm/storypage_comment.html
http://121.243.211.187/vishal/html/loverealm/storypage_share.html
http://121.243.211.187/vishal/html/loverealm/
